### ISSUE TITLE
costoss

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/practica-de-costos-bjny-huerto2#1]
[ANÁLISIS DE COSTOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-bjny-huerto2/files/8129712/ANALISIS.DE.COSTOS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 19.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
